[package]
name = "Chumsky_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.5"
chumsky = "1.0.0-alpha.2"
features = "0.10.0"
miette = "5.5.0"
